description: "Sets the icon of a workspace."
enabled: true
entry_point: run.py
name: admin.teams.settings.setIcon
parameters:
  end_point:
    default: admin.teams.settings.setIcon
    immutable: true
    type: string
  http_method:
    default: GET
    required: true
    type: string
  image_url:
    required: true
    description: "Image URL for the icon"
    type: string
  team_id:
    required: true
    description: "ID for the workspace to set the icon for."
    type: string
  token:
    required: false
    description: "Authentication token. Requires scope: `admin.teams:write`"
    type: string
runner_type: python-script
