description: "Set the name of a given workspace."
enabled: true
entry_point: run.py
name: admin.teams.settings.setName
parameters:
  end_point:
    default: admin.teams.settings.setName
    immutable: true
    type: string
  http_method:
    default: POST
    required: true
    type: string
  name:
    required: true
    description: "The new name of the workspace."
    type: string
  team_id:
    required: true
    description: "ID for the workspace to set the name for."
    type: string
  token:
    required: false
    description: "Authentication token. Requires scope: `admin.teams:write`"
    type: string
runner_type: python-script
