description: "Set the default channels of a workspace."
enabled: true
entry_point: run.py
name: admin.teams.settings.setDefaultChannels
parameters:
  end_point:
    default: admin.teams.settings.setDefaultChannels
    immutable: true
    type: string
  http_method:
    default: GET
    required: true
    type: string
  channel_ids:
    required: true
    description: "An array of channel IDs."
    type: string
  team_id:
    required: true
    description: "ID for the workspace to set the default channel for."
    type: string
  token:
    required: false
    description: "Authentication token. Requires scope: `admin.teams:write`"
    type: string
runner_type: python-script
