description: "An API method that allows admins to set the discoverability of a given workspace"
enabled: true
entry_point: run.py
name: admin.teams.settings.setDiscoverability
parameters:
  end_point:
    default: admin.teams.settings.setDiscoverability
    immutable: true
    type: string
  http_method:
    default: POST
    required: true
    type: string
  discoverability:
    required: true
    description: "This workspace\u0027s discovery setting. It must be set to one of `open`, `invite_only`, `closed`, or `unlisted`."
    type: string
  team_id:
    required: true
    description: "The ID of the workspace to set discoverability on."
    type: string
  token:
    required: false
    description: "Authentication token. Requires scope: `admin.teams:write`"
    type: string
runner_type: python-script
